"""empty message

Revision ID: 3bf875267756
Revises: b514bd128fb0
Create Date: 2023-04-13 11:14:37.787672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf875267756'
down_revision = 'b514bd128fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['user.id'], name='fk_follows_followee_id'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='fk_follows_follower_id'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
